---
name: codecov.io-status
description: "Reports codecov status on a pull request"
branding:
  icon: activity
  color: purple
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: pip
        python-version: "3.12"

    - name: Run ansible-lint
      shell: bash
      run: python3 codecov-status.py
