[tool.pylint."MESSAGES CONTROL"]
# increase from default is 50 which is too aggressive
max-statements = 60
disable = [
  # Disabled on purpose:
  "line-too-long", # covered by black
  "invalid-name",
]
